--[dbo].[mas_Alcoba]
INSERT INTO mas_Alcoba(Descripcion) VALUES ('0')
INSERT INTO mas_Alcoba(Descripcion) VALUES ('1')
INSERT INTO mas_Alcoba(Descripcion) VALUES ('2')
INSERT INTO mas_Alcoba(Descripcion) VALUES ('3')
INSERT INTO mas_Alcoba(Descripcion) VALUES ('4')
INSERT INTO mas_Alcoba(Descripcion) VALUES ('5')
INSERT INTO mas_Alcoba(Descripcion) VALUES ('6')
INSERT INTO mas_Alcoba(Descripcion) VALUES ('7')
INSERT INTO mas_Alcoba(Descripcion) VALUES ('8')
INSERT INTO mas_Alcoba(Descripcion) VALUES ('9')
INSERT INTO mas_Alcoba(Descripcion) VALUES ('10')
INSERT INTO mas_Alcoba(Descripcion) VALUES ('11')
INSERT INTO mas_Alcoba(Descripcion) VALUES ('12')
INSERT INTO mas_Alcoba(Descripcion) VALUES ('13')
INSERT INTO mas_Alcoba(Descripcion) VALUES ('14')
INSERT INTO mas_Alcoba(Descripcion) VALUES ('15')
INSERT INTO mas_Alcoba(Descripcion) VALUES ('16')
INSERT INTO mas_Alcoba(Descripcion) VALUES ('17')
INSERT INTO mas_Alcoba(Descripcion) VALUES ('18')
INSERT INTO mas_Alcoba(Descripcion) VALUES ('19')
INSERT INTO mas_Alcoba(Descripcion) VALUES ('20')
INSERT INTO mas_Alcoba(Descripcion) VALUES ('21')
INSERT INTO mas_Alcoba(Descripcion) VALUES ('22')
INSERT INTO mas_Alcoba(Descripcion) VALUES ('23')
INSERT INTO mas_Alcoba(Descripcion) VALUES ('24')
INSERT INTO mas_Alcoba(Descripcion) VALUES ('25')
INSERT INTO mas_Alcoba(Descripcion) VALUES ('26')
INSERT INTO mas_Alcoba(Descripcion) VALUES ('27')
INSERT INTO mas_Alcoba(Descripcion) VALUES ('28')
INSERT INTO mas_Alcoba(Descripcion) VALUES ('29')
INSERT INTO mas_Alcoba(Descripcion) VALUES ('>30')

--[dbo].[mas_Bano]
INSERT INTO mas_Bano(Descripcion) VALUES ('0')
INSERT INTO mas_Bano(Descripcion) VALUES ('1')
INSERT INTO mas_Bano(Descripcion) VALUES ('2')
INSERT INTO mas_Bano(Descripcion) VALUES ('3')
INSERT INTO mas_Bano(Descripcion) VALUES ('4')
INSERT INTO mas_Bano(Descripcion) VALUES ('5')
INSERT INTO mas_Bano(Descripcion) VALUES ('6')
INSERT INTO mas_Bano(Descripcion) VALUES ('7')
INSERT INTO mas_Bano(Descripcion) VALUES ('8')
INSERT INTO mas_Bano(Descripcion) VALUES ('9')
INSERT INTO mas_Bano(Descripcion) VALUES ('>10')

--[dbo].[mas_CaracteristicaExterna]
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Acceso pavimentado')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Árboles frutales')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Áreaa social')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Áreas Turísticas')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Ascensor')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Barbacoa/Parrilla/Quincho')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Bosques nativos')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Bungalow/Paradero')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Calles de Tosca')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Cancha de baloncesto')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Cancha de futbol')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Cancha de squash')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Cancha de tenis')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Centro comerciales')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Cerca zona urbana')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Circuito cerrado de TV')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Club House')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Club social')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Cochera/Garaje')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Colegios/Universidades')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Establo')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Galpón')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Garaje')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Garita de Entrada')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Gimnasio')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Invernadero')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Jardín')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Jaula de golf')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Kiosko')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Lago')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Laguna')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Montaña')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Oficina de negocios')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Parquedero visitantes')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Paques cercanos')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Patio')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Pesebrera')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Piscina')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Pista de Padel')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Planta electrica')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Playas')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Portería/Recepción')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Pozo de agua natura')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Río/Quebrada cercana')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Sala de internet')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Salón comunal')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Sistema de riego')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Sobre vía principal')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Terraza')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Trans. público cercano')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Trastero')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Urbanización cerrada')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Vigilancia')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Vivienda bifamiliar')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Vivienda multifamiliar')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Vivienda unifamiliar')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Zona campestre')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Zona camping')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Zona comercial')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Zona industrial')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Zona infantil')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Zona residencial')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Zonas deportivas')
INSERT INTO mas_CaracteristicaExterna(Descripcion) VALUES ('Zona verdes')

--[dbo].[mas_CaracteristicaInterna]
INSERT INTO mas_CaracteristicaInterna(Descripcion) VALUES ('Adosado')
INSERT INTO mas_CaracteristicaInterna(Descripcion) VALUES ('Aire Acondicionado')
INSERT INTO mas_CaracteristicaInterna(Descripcion) VALUES ('Alarma')
INSERT INTO mas_CaracteristicaInterna(Descripcion) VALUES ('Amoblado')
INSERT INTO mas_CaracteristicaInterna(Descripcion) VALUES ('Armarios Empotrados')
INSERT INTO mas_CaracteristicaInterna(Descripcion) VALUES ('Balcón')
INSERT INTO mas_CaracteristicaInterna(Descripcion) VALUES ('Baño Auxiliar')
INSERT INTO mas_CaracteristicaInterna(Descripcion) VALUES ('Baño en habitación')
INSERT INTO mas_CaracteristicaInterna(Descripcion) VALUES ('Barra estilo americano')
INSERT INTO mas_CaracteristicaInterna(Descripcion) VALUES ('Biblioteca/Estudio')
INSERT INTO mas_CaracteristicaInterna(Descripcion) VALUES ('Bifamiliar')
INSERT INTO mas_CaracteristicaInterna(Descripcion) VALUES ('Calentador')
INSERT INTO mas_CaracteristicaInterna(Descripcion) VALUES ('Chimenea')
INSERT INTO mas_CaracteristicaInterna(Descripcion) VALUES ('Citófono/Intercomunicador')
INSERT INTO mas_CaracteristicaInterna(Descripcion) VALUES ('Clósets')
INSERT INTO mas_CaracteristicaInterna(Descripcion) VALUES ('Cocina equipada')
INSERT INTO mas_CaracteristicaInterna(Descripcion) VALUES ('Cocina integral')
INSERT INTO mas_CaracteristicaInterna(Descripcion) VALUES ('Cocina tio americano')
INSERT INTO mas_CaracteristicaInterna(Descripcion) VALUES ('Comedor auxiliar')
INSERT INTO mas_CaracteristicaInterna(Descripcion) VALUES ('Depósito')
INSERT INTO mas_CaracteristicaInterna(Descripcion) VALUES ('Despensa')
INSERT INTO mas_CaracteristicaInterna(Descripcion) VALUES ('Doble ventana')
INSERT INTO mas_CaracteristicaInterna(Descripcion) VALUES ('Gas domiciliario')
INSERT INTO mas_CaracteristicaInterna(Descripcion) VALUES ('Habitación conductores')
INSERT INTO mas_CaracteristicaInterna(Descripcion) VALUES ('Habitación servicio')
INSERT INTO mas_CaracteristicaInterna(Descripcion) VALUES ('Hall de alcobas')
INSERT INTO mas_CaracteristicaInterna(Descripcion) VALUES ('Hospedaje Turismo')
INSERT INTO mas_CaracteristicaInterna(Descripcion) VALUES ('Jacuzzi')
INSERT INTO mas_CaracteristicaInterna(Descripcion) VALUES ('Reformado')
INSERT INTO mas_CaracteristicaInterna(Descripcion) VALUES ('Sauna')
INSERT INTO mas_CaracteristicaInterna(Descripcion) VALUES ('Suelo de cerámica/Mármol')
INSERT INTO mas_CaracteristicaInterna(Descripcion) VALUES ('Trastero')
INSERT INTO mas_CaracteristicaInterna(Descripcion) VALUES ('Trifamiliar')
INSERT INTO mas_CaracteristicaInterna(Descripcion) VALUES ('Turco')
INSERT INTO mas_CaracteristicaInterna(Descripcion) VALUES ('Unifamiliar')
INSERT INTO mas_CaracteristicaInterna(Descripcion) VALUES ('Vista panorámica')
INSERT INTO mas_CaracteristicaInterna(Descripcion) VALUES ('Zona de lavandería')

--[dbo].[mas_Ciudad]
--PENDIENTE

--[dbo].[mas_Departamento]
--PENDIENTE

--[dbo].[mas_Empresa]
--PENDIENTE

--[dbo].[mas_EstadoCartera]
INSERT INTO mas_EstadoCartera(Descripcion) VALUES ('Al dia')
INSERT INTO mas_EstadoCartera(Descripcion) VALUES ('Pendiente')
INSERT INTO mas_EstadoCartera(Descripcion) VALUES ('Mora')

--[dbo].[mas_EstadoUsuario]
INSERT INTO mas_EstadoUsuario(Descripcion) VALUES ('Nuevo')
INSERT INTO mas_EstadoUsuario(Descripcion) VALUES ('En proceso')
INSERT INTO mas_EstadoUsuario(Descripcion) VALUES ('Convertido')
INSERT INTO mas_EstadoUsuario(Descripcion) VALUES ('Recuperado')
INSERT INTO mas_EstadoUsuario(Descripcion) VALUES ('Perdido')

--[dbo].[mas_EstadoFisicoPropiedad]
INSERT INTO mas_EstadoFisicoPropiedad(Descripcion) VALUES ('Usado')
INSERT INTO mas_EstadoFisicoPropiedad(Descripcion) VALUES ('Nuevo')
INSERT INTO mas_EstadoFisicoPropiedad(Descripcion) VALUES ('Proyecto')
INSERT INTO mas_EstadoFisicoPropiedad(Descripcion) VALUES ('En construcción')

--[dbo].[mas_EstadoProyecto]
INSERT INTO mas_EstadoProyecto(Descripcion) VALUES ('En financiamiento')
INSERT INTO mas_EstadoProyecto(Descripcion) VALUES ('En ejecucion')
INSERT INTO mas_EstadoProyecto(Descripcion) VALUES ('Finalizado')

--[dbo].[mas_EstadoPublicacion]
INSERT INTO mas_EstadoPublicacion(Descripcion) VALUES ('Activo')
INSERT INTO mas_EstadoPublicacion(Descripcion) VALUES ('Inactivo')

--[dbo].[mas_Estrato]
INSERT INTO mas_Estrato(Descripcion) VALUES ('N/D')
INSERT INTO mas_Estrato(Descripcion) VALUES ('1')
INSERT INTO mas_Estrato(Descripcion) VALUES ('2')
INSERT INTO mas_Estrato(Descripcion) VALUES ('3')
INSERT INTO mas_Estrato(Descripcion) VALUES ('4')
INSERT INTO mas_Estrato(Descripcion) VALUES ('5')
INSERT INTO mas_Estrato(Descripcion) VALUES ('6')
INSERT INTO mas_Estrato(Descripcion) VALUES ('Rural')
INSERT INTO mas_Estrato(Descripcion) VALUES ('Comercial')

--[dbo].[mas_Funcionalidad]
--PENDIENTE

--[dbo].[mas_Garaje]
INSERT INTO mas_Garaje(Descripcion) VALUES ('0 Vehiculos')
INSERT INTO mas_Garaje(Descripcion) VALUES ('1 Vehiculos')
INSERT INTO mas_Garaje(Descripcion) VALUES ('2 Vehiculos')
INSERT INTO mas_Garaje(Descripcion) VALUES ('3 Vehiculos')
INSERT INTO mas_Garaje(Descripcion) VALUES ('4 Vehiculos')
INSERT INTO mas_Garaje(Descripcion) VALUES ('5 Vehiculos')
INSERT INTO mas_Garaje(Descripcion) VALUES ('6 Vehiculos')
INSERT INTO mas_Garaje(Descripcion) VALUES ('7 Vehiculos')
INSERT INTO mas_Garaje(Descripcion) VALUES ('8 Vehiculos')
INSERT INTO mas_Garaje(Descripcion) VALUES ('9 Vehiculos')
INSERT INTO mas_Garaje(Descripcion) VALUES ('10 Vehiculos')
INSERT INTO mas_Garaje(Descripcion) VALUES ('11 Vehiculos')
INSERT INTO mas_Garaje(Descripcion) VALUES ('12 Vehiculos')
INSERT INTO mas_Garaje(Descripcion) VALUES ('13 Vehiculos')
INSERT INTO mas_Garaje(Descripcion) VALUES ('14 Vehiculos')
INSERT INTO mas_Garaje(Descripcion) VALUES ('15 Vehiculos')
INSERT INTO mas_Garaje(Descripcion) VALUES ('16 Vehiculos')
INSERT INTO mas_Garaje(Descripcion) VALUES ('17 Vehiculos')
INSERT INTO mas_Garaje(Descripcion) VALUES ('18 Vehiculos')
INSERT INTO mas_Garaje(Descripcion) VALUES ('19 Vehiculos')
INSERT INTO mas_Garaje(Descripcion) VALUES ('20 Vehiculos')
INSERT INTO mas_Garaje(Descripcion) VALUES ('21 Vehiculos')
INSERT INTO mas_Garaje(Descripcion) VALUES ('22 Vehiculos')
INSERT INTO mas_Garaje(Descripcion) VALUES ('23 Vehiculos')
INSERT INTO mas_Garaje(Descripcion) VALUES ('24 Vehiculos')
INSERT INTO mas_Garaje(Descripcion) VALUES ('25 Vehiculos')
INSERT INTO mas_Garaje(Descripcion) VALUES ('26 Vehiculos')
INSERT INTO mas_Garaje(Descripcion) VALUES ('27 Vehiculos')
INSERT INTO mas_Garaje(Descripcion) VALUES ('28 Vehiculos')
INSERT INTO mas_Garaje(Descripcion) VALUES ('29 Vehiculos')
INSERT INTO mas_Garaje(Descripcion) VALUES ('30 Vehiculos')

--[dbo].[mas_MedioCaptacion]
INSERT INTO mas_MedioCaptacion(Descripcion) VALUES ('Ninguno')
INSERT INTO mas_MedioCaptacion(Descripcion) VALUES ('Portal inmobiliario')

--[dbo].[mas_Pais]
--PENDIENTE

--[dbo].[mas_Permiso]
--PENDIENTE

--[dbo].[mas_PermisoRol]
--PENDIENTE

--[dbo].[mas_Piso]
INSERT INTO mas_Piso(Descripcion) VALUES ('N/D')
INSERT INTO mas_Piso(Descripcion) VALUES ('1')
INSERT INTO mas_Piso(Descripcion) VALUES ('2')
INSERT INTO mas_Piso(Descripcion) VALUES ('3')
INSERT INTO mas_Piso(Descripcion) VALUES ('4')
INSERT INTO mas_Piso(Descripcion) VALUES ('5')
INSERT INTO mas_Piso(Descripcion) VALUES ('6')
INSERT INTO mas_Piso(Descripcion) VALUES ('7')
INSERT INTO mas_Piso(Descripcion) VALUES ('8')
INSERT INTO mas_Piso(Descripcion) VALUES ('9')
INSERT INTO mas_Piso(Descripcion) VALUES ('10')
INSERT INTO mas_Piso(Descripcion) VALUES ('11')
INSERT INTO mas_Piso(Descripcion) VALUES ('12')
INSERT INTO mas_Piso(Descripcion) VALUES ('13')
INSERT INTO mas_Piso(Descripcion) VALUES ('14')
INSERT INTO mas_Piso(Descripcion) VALUES ('15')
INSERT INTO mas_Piso(Descripcion) VALUES ('16')
INSERT INTO mas_Piso(Descripcion) VALUES ('17')
INSERT INTO mas_Piso(Descripcion) VALUES ('18')
INSERT INTO mas_Piso(Descripcion) VALUES ('19')
INSERT INTO mas_Piso(Descripcion) VALUES ('20')
INSERT INTO mas_Piso(Descripcion) VALUES ('21')
INSERT INTO mas_Piso(Descripcion) VALUES ('22')
INSERT INTO mas_Piso(Descripcion) VALUES ('23')
INSERT INTO mas_Piso(Descripcion) VALUES ('24')
INSERT INTO mas_Piso(Descripcion) VALUES ('25')
INSERT INTO mas_Piso(Descripcion) VALUES ('26')
INSERT INTO mas_Piso(Descripcion) VALUES ('27')
INSERT INTO mas_Piso(Descripcion) VALUES ('28')
INSERT INTO mas_Piso(Descripcion) VALUES ('29')
INSERT INTO mas_Piso(Descripcion) VALUES ('30')
INSERT INTO mas_Piso(Descripcion) VALUES ('31')
INSERT INTO mas_Piso(Descripcion) VALUES ('32')
INSERT INTO mas_Piso(Descripcion) VALUES ('33')
INSERT INTO mas_Piso(Descripcion) VALUES ('34')
INSERT INTO mas_Piso(Descripcion) VALUES ('35')
INSERT INTO mas_Piso(Descripcion) VALUES ('36')
INSERT INTO mas_Piso(Descripcion) VALUES ('37')
INSERT INTO mas_Piso(Descripcion) VALUES ('38')
INSERT INTO mas_Piso(Descripcion) VALUES ('39')
INSERT INTO mas_Piso(Descripcion) VALUES ('40')
INSERT INTO mas_Piso(Descripcion) VALUES ('41')
INSERT INTO mas_Piso(Descripcion) VALUES ('42')
INSERT INTO mas_Piso(Descripcion) VALUES ('43')
INSERT INTO mas_Piso(Descripcion) VALUES ('44')
INSERT INTO mas_Piso(Descripcion) VALUES ('45')
INSERT INTO mas_Piso(Descripcion) VALUES ('46')
INSERT INTO mas_Piso(Descripcion) VALUES ('47')
INSERT INTO mas_Piso(Descripcion) VALUES ('48')
INSERT INTO mas_Piso(Descripcion) VALUES ('49')
INSERT INTO mas_Piso(Descripcion) VALUES ('50')
INSERT INTO mas_Piso(Descripcion) VALUES ('51')
INSERT INTO mas_Piso(Descripcion) VALUES ('52')
INSERT INTO mas_Piso(Descripcion) VALUES ('53')
INSERT INTO mas_Piso(Descripcion) VALUES ('54')
INSERT INTO mas_Piso(Descripcion) VALUES ('55')
INSERT INTO mas_Piso(Descripcion) VALUES ('56')
INSERT INTO mas_Piso(Descripcion) VALUES ('57')
INSERT INTO mas_Piso(Descripcion) VALUES ('58')
INSERT INTO mas_Piso(Descripcion) VALUES ('59')
INSERT INTO mas_Piso(Descripcion) VALUES ('60')

--[dbo].[mas_Portal]
--PENDIENTE

--[dbo].[mas_Rol]
--PENDIENTE

--[dbo].[mas_Tiempo]
INSERT INTO mas_Tiempo(Descripcion) VALUES ('Mensual')
INSERT INTO mas_Tiempo(Descripcion) VALUES ('Semanal')
INSERT INTO mas_Tiempo(Descripcion) VALUES ('Quincenal')
INSERT INTO mas_Tiempo(Descripcion) VALUES ('Diario')

--[dbo].[mas_TipoUsuario]
INSERT INTO mas_TipoUsuario(Descripcion) VALUES ('Administrador')
INSERT INTO mas_TipoUsuario(Descripcion) VALUES ('Gestor inmobiliario')
INSERT INTO mas_TipoUsuario(Descripcion) VALUES ('Vendedor')
INSERT INTO mas_TipoUsuario(Descripcion) VALUES ('Comprador')
INSERT INTO mas_TipoUsuario(Descripcion) VALUES ('Propieario')
INSERT INTO mas_TipoUsuario(Descripcion) VALUES ('Inquilino')
INSERT INTO mas_TipoUsuario(Descripcion) VALUES ('Codeudor')
INSERT INTO mas_TipoUsuario(Descripcion) VALUES ('Inversionista')

--[dbo].[mas_TipoInmueble]
INSERT INTO mas_TipoInmueble(Descripcion) VALUES ('Apartaestudio')
INSERT INTO mas_TipoInmueble(Descripcion) VALUES ('Apartamento')
INSERT INTO mas_TipoInmueble(Descripcion) VALUES ('Bodega')
INSERT INTO mas_TipoInmueble(Descripcion) VALUES ('Bungalow')
INSERT INTO mas_TipoInmueble(Descripcion) VALUES ('Cabaña')
INSERT INTO mas_TipoInmueble(Descripcion) VALUES ('Campestre')
INSERT INTO mas_TipoInmueble(Descripcion) VALUES ('Campos, Chacras y Quintas')
INSERT INTO mas_TipoInmueble(Descripcion) VALUES ('Casa')
INSERT INTO mas_TipoInmueble(Descripcion) VALUES ('Casa Playa')
INSERT INTO mas_TipoInmueble(Descripcion) VALUES ('Chalet')
INSERT INTO mas_TipoInmueble(Descripcion) VALUES ('Condominio')
INSERT INTO mas_TipoInmueble(Descripcion) VALUES ('Consultorio')
INSERT INTO mas_TipoInmueble(Descripcion) VALUES ('Cortijo')
INSERT INTO mas_TipoInmueble(Descripcion) VALUES ('Duplex')
INSERT INTO mas_TipoInmueble(Descripcion) VALUES ('Edificio')
INSERT INTO mas_TipoInmueble(Descripcion) VALUES ('Finca')
INSERT INTO mas_TipoInmueble(Descripcion) VALUES ('Finca - Hoteles')
INSERT INTO mas_TipoInmueble(Descripcion) VALUES ('Galpón Industrial')
INSERT INTO mas_TipoInmueble(Descripcion) VALUES ('Garaje')
INSERT INTO mas_TipoInmueble(Descripcion) VALUES ('Hostal')
INSERT INTO mas_TipoInmueble(Descripcion) VALUES ('Hoteles')
INSERT INTO mas_TipoInmueble(Descripcion) VALUES ('Isla')
INSERT INTO mas_TipoInmueble(Descripcion) VALUES ('Local')
INSERT INTO mas_TipoInmueble(Descripcion) VALUES ('Lote')
INSERT INTO mas_TipoInmueble(Descripcion) VALUES ('Lote Comercial')
INSERT INTO mas_TipoInmueble(Descripcion) VALUES ('Lote de Playa')
INSERT INTO mas_TipoInmueble(Descripcion) VALUES ('Nave Industrial')
INSERT INTO mas_TipoInmueble(Descripcion) VALUES ('Oficina')
INSERT INTO mas_TipoInmueble(Descripcion) VALUES ('Penthouse')
INSERT INTO mas_TipoInmueble(Descripcion) VALUES ('Piso Terreno')

--[dbo].[mas_TipoMoneda]
INSERT INTO mas_TipoMoneda(Descripcion) VALUES ('Pesos Colombianos')
INSERT INTO mas_TipoMoneda(Descripcion) VALUES ('Pesos Argentinos')
INSERT INTO mas_TipoMoneda(Descripcion) VALUES ('Dólares Americanos')
INSERT INTO mas_TipoMoneda(Descripcion) VALUES ('Euros')
INSERT INTO mas_TipoMoneda(Descripcion) VALUES ('Pesos Dominicanos')
INSERT INTO mas_TipoMoneda(Descripcion) VALUES ('Pesos Chilenos')
INSERT INTO mas_TipoMoneda(Descripcion) VALUES ('Soles')
INSERT INTO mas_TipoMoneda(Descripcion) VALUES ('Boliviano')
INSERT INTO mas_TipoMoneda(Descripcion) VALUES ('Colón Costarricense')
INSERT INTO mas_TipoMoneda(Descripcion) VALUES ('Quetzal')
INSERT INTO mas_TipoMoneda(Descripcion) VALUES ('Lempira')
INSERT INTO mas_TipoMoneda(Descripcion) VALUES ('Pesos Uruguayos')
INSERT INTO mas_TipoMoneda(Descripcion) VALUES ('U')
INSERT INTO mas_TipoMoneda(Descripcion) VALUES ('Guarani')
INSERT INTO mas_TipoMoneda(Descripcion) VALUES ('Libra Esterlina')
INSERT INTO mas_TipoMoneda(Descripcion) VALUES ('Florínes')
INSERT INTO mas_TipoMoneda(Descripcion) VALUES ('Bolívares')
INSERT INTO mas_TipoMoneda(Descripcion) VALUES ('Reales')

--[dbo].[mas_TipoNegocio]
INSERT INTO mas_TipoNegocio(Descripcion) VALUES ('Venta')
INSERT INTO mas_TipoNegocio(Descripcion) VALUES ('Alquiler')

--[dbo].[mas_TipoPago]
INSERT INTO mas_TipoPago(Descripcion) VALUES ('Franquicia')
INSERT INTO mas_TipoPago(Descripcion) VALUES ('Alquiler')
INSERT INTO mas_TipoPago(Descripcion) VALUES ('Compra')
INSERT INTO mas_TipoPago(Descripcion) VALUES ('Inversión')

--[dbo].[mas_TipoPersona]
INSERT INTO mas_TipoPersona(Descripcion) VALUES ('Independiente')
INSERT INTO mas_TipoPersona(Descripcion) VALUES ('Jurídica')
INSERT INTO mas_TipoPersona(Descripcion) VALUES ('Empleado')
INSERT INTO mas_TipoPersona(Descripcion) VALUES ('Pensionado')

--[dbo].[mas_TipoUsuario]
INSERT INTO mas_TipoUsuario(Descripcion) VALUES ('Administrador')
INSERT INTO mas_TipoUsuario(Descripcion) VALUES ('Usuario')

--[dbo].[mas_ZonaBarrio]
--PENDIENTE

--[dbo].[mas_ZonaGeografica]
--PENDIENTE
